# Generated by Django 2.2.5 on 2019-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinfo',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]