# Generated by Django 2.2.5 on 2019-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0003_modelsinfo_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
                ('subject', models.CharField(default='', max_length=120)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]