# Generated by Django 2.2.5 on 2019-12-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation_cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MitigationsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigations_cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliciesCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliciesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SdgsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdgs_cat', models.TextField()),
                ('sdgs_title', models.TextField()),
                ('ordering', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SectorCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocioeconsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socioecons_cat', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SocioeconsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socioecons_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocioeconsStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
                ('socioecons_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.SocioeconsName')),
            ],
        ),
        migrations.AddField(
            model_name='socioeconsname',
            name='model_id',
            field=models.ManyToManyField(through='i2amparis_main.SocioeconsStates', to='i2amparis_main.ModelsInfo'),
        ),
        migrations.AddField(
            model_name='socioeconsname',
            name='socioecons_cat_id',
            field=models.ManyToManyField(to='i2amparis_main.SocioeconsCat'),
        ),
        migrations.CreateModel(
            name='SocioeconsIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socioecons_icons', models.TextField()),
                ('socioecons_cat_id', models.ManyToManyField(to='i2amparis_main.SocioeconsCat')),
            ],
        ),
        migrations.CreateModel(
            name='SectorSubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_sub_cat', models.TextField(default='')),
                ('sector_cat_id', models.ManyToManyField(to='i2amparis_main.SectorCat')),
            ],
        ),
        migrations.CreateModel(
            name='SectorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.TextField()),
                ('model_id', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
                ('sector_sub_cat', models.ManyToManyField(to='i2amparis_main.SectorSubCat')),
            ],
        ),
        migrations.CreateModel(
            name='SectorIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_icon', models.TextField()),
                ('sector_cat_id', models.ManyToManyField(to='i2amparis_main.SectorCat')),
            ],
        ),
        migrations.CreateModel(
            name='SdgsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdgs_name', models.TextField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
                ('sdgs_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.SdgsCat')),
            ],
        ),
        migrations.CreateModel(
            name='SdgsIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdgs_icon', models.TextField(default='')),
                ('sdgs_cat_id', models.ManyToManyField(to='i2amparis_main.SdgsCat')),
            ],
        ),
        migrations.AddField(
            model_name='sdgscat',
            name='model_id',
            field=models.ManyToManyField(through='i2amparis_main.SdgsName', to='i2amparis_main.ModelsInfo'),
        ),
        migrations.CreateModel(
            name='PoliciesStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
                ('policies_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.PoliciesName')),
            ],
        ),
        migrations.AddField(
            model_name='policiesname',
            name='model_id',
            field=models.ManyToManyField(through='i2amparis_main.PoliciesStates', to='i2amparis_main.ModelsInfo'),
        ),
        migrations.AddField(
            model_name='policiesname',
            name='policies_cat_id',
            field=models.ManyToManyField(to='i2amparis_main.PoliciesCat'),
        ),
        migrations.CreateModel(
            name='PoliciesIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_icon', models.TextField()),
                ('policies_cat', models.ManyToManyField(to='i2amparis_main.PoliciesCat')),
            ],
        ),
        migrations.CreateModel(
            name='MitigationsSubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigations_sub_cat', models.TextField(default='')),
                ('mitigations_cat_id', models.ManyToManyField(to='i2amparis_main.MitigationsCat')),
            ],
        ),
        migrations.CreateModel(
            name='MitigationsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigations_name', models.TextField()),
                ('mitigations_sub_cat_id', models.ManyToManyField(to='i2amparis_main.MitigationsSubCat')),
                ('model_id', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MitigationsIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigation_icon', models.TextField()),
                ('mitigation_cat_id', models.ManyToManyField(to='i2amparis_main.MitigationsCat')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionsStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('emissions_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.EmissionsName')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.AddField(
            model_name='emissionsname',
            name='model_id',
            field=models.ManyToManyField(through='i2amparis_main.EmissionsStates', to='i2amparis_main.ModelsInfo'),
        ),
        migrations.CreateModel(
            name='EmissionsIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions_icon_name', models.TextField()),
                ('emission_name', models.ManyToManyField(to='i2amparis_main.EmissionsName')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation_name', models.TextField()),
                ('adaptation_cat_id', models.ManyToManyField(to='i2amparis_main.AdaptationCat')),
                ('model_id', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptationIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation_icon', models.TextField()),
                ('adaptation_cat_id', models.ManyToManyField(to='i2amparis_main.AdaptationCat')),
            ],
        ),
    ]
