# Generated by Django 2.2.5 on 2019-12-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0006_auto_20191216_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorname',
            name='ordering',
            field=models.IntegerField(default=3),
        ),
    ]
