# Generated by Django 2.2.5 on 2019-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0007_auto_20191216_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorname',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
