# Generated by Django 2.2.5 on 2020-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0009_auto_20200121_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmonisation_Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(default='-', max_length=50)),
                ('var_title', models.CharField(default='-', max_length=50)),
                ('var_category', models.CharField(default='-', max_length=50)),
                ('var_definition', models.TextField(default='-')),
                ('var_unit', models.CharField(default='-', max_length=20)),
                ('var_source_info', models.TextField(default='-')),
            ],
        ),
    ]
