# Generated by Django 2.2.5 on 2020-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0010_harmonisation_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinfo',
            name='coverage_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modelsinfo',
            name='harmonisation',
            field=models.BooleanField(default=False),
        ),
    ]
