# Generated by Django 2.2.5 on 2020-07-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0011_auto_20200630_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_status', models.CharField(default='', max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.Harmonisation_Variables')),
            ],
        ),
        migrations.AddField(
            model_name='harmonisation_variables',
            name='model_relation',
            field=models.ManyToManyField(through='i2amparis_main.HarmData', to='i2amparis_main.ModelsInfo'),
        ),
    ]
