# Generated by Django 2.2.5 on 2020-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0012_auto_20200702_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harmonisation_variables',
            name='var_source_info',
        ),
        migrations.RemoveField(
            model_name='harmonisation_variables',
            name='var_unit',
        ),
        migrations.AddField(
            model_name='harmdata',
            name='var_source_info',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='harmdata',
            name='var_timespan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='harmdata',
            name='var_unit',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
