# Generated by Django 2.2.5 on 2020-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0013_auto_20200720_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmdata',
            name='var_source_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='harmdata',
            name='var_unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='harmonisation_variables',
            name='var_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='harmonisation_variables',
            name='var_definition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='harmonisation_variables',
            name='var_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='harmonisation_variables',
            name='var_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
