# Generated by Django 2.2.5 on 2020-07-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0015_dataset_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='dataset_relation',
        ),
        migrations.AddField(
            model_name='variable',
            name='dataset_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.Dataset'),
            preserve_default=False,
        ),
    ]
