# Generated by Django 2.2.5 on 2020-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0016_auto_20200721_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVariableHarmonisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=50)),
                ('variable', models.CharField(default='', max_length=50)),
                ('io_status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataVariableHarmonisationGuides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_from', models.CharField(default='', max_length=50)),
                ('guide_to', models.CharField(default='', max_length=50)),
                ('value', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_format',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
