# Generated by Django 2.2.5 on 2020-07-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0017_auto_20200722_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datavariableharmonisation',
            old_name='io_status',
            new_name='harmonisation_io_status',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_format',
        ),
        migrations.RemoveField(
            model_name='datavariableharmonisation',
            name='model',
        ),
        migrations.RemoveField(
            model_name='datavariableharmonisation',
            name='variable',
        ),
        migrations.AddField(
            model_name='datavariableharmonisation',
            name='harmonisation_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datavariableharmonisation',
            name='harmonisation_variable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.Harmonisation_Variables'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_table_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
