# Generated by Django 2.2.5 on 2020-07-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0018_auto_20200731_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmonisation_variables',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
