# Generated by Django 2.2.5 on 2020-07-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0019_harmonisation_variables_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataset',
            new_name='IDataset',
        ),
    ]
