# Generated by Django 2.2.5 on 2020-07-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0020_auto_20200731_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IDataset',
            new_name='Dataset',
        ),
    ]
