# Generated by Django 2.2.5 on 2020-07-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0021_auto_20200731_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
