# Generated by Django 2.2.5 on 2020-07-31 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0023_dataset_dataset_django_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHarmonisationVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='datavariableharmonisation',
            name='harmonisation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataModels'),
        ),
        migrations.AlterField(
            model_name='datavariableharmonisation',
            name='harmonisation_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataHarmonisationVariables'),
        ),
    ]
