# Generated by Django 2.2.5 on 2020-07-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0024_auto_20200731_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVariableHarmonisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harmonisation_io_status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataVariablesHarmonisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DataVariablesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField(default='')),
                ('type', models.TextField()),
                ('time_horizon', models.IntegerField()),
                ('time_steps_in_solution', models.IntegerField(default=0)),
                ('ordering', models.IntegerField(default=0)),
                ('coverage', models.TextField(default='')),
                ('coverage_title', models.TextField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='DataVariableHarmonisationGuides',
            new_name='DatasetVariableHarmonisationGuides',
        ),
        migrations.RemoveField(
            model_name='datavariableharmonisation',
            name='harmonisation_model',
        ),
        migrations.RemoveField(
            model_name='datavariableharmonisation',
            name='harmonisation_variable',
        ),
        migrations.DeleteModel(
            name='DataHarmonisationVariables',
        ),
        migrations.DeleteModel(
            name='DataModels',
        ),
        migrations.DeleteModel(
            name='DataVariableHarmonisation',
        ),
    ]
