# Generated by Django 2.2.5 on 2020-07-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0025_auto_20200731_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetvariableharmonisation',
            name='harmonisation_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetvariableharmonisation',
            name='harmonisation_variable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesHarmonisation'),
            preserve_default=False,
        ),
    ]
