# Generated by Django 2.2.5 on 2020-09-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0029_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
