# Generated by Django 3.0.5 on 2020-09-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0030_delete_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionsRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScenariosRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitsRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VariablesRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.RegionsRes')),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ScenariosRes')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.UnitsRes')),
                ('variable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.VariablesRes')),
            ],
        ),
    ]
