# Generated by Django 2.2.5 on 2020-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0032_harmdatanew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonisation_variables',
            name='model_relation',
            field=models.ManyToManyField(through='i2amparis_main.HarmDataNew', to='i2amparis_main.DataVariablesModels'),
        ),
    ]
