# Generated by Django 2.2.5 on 2020-10-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0033_auto_20201014_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOnDemandVariableHarmonisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_status', models.CharField(default='', max_length=50)),
                ('var_unit', models.CharField(default='', max_length=20)),
                ('var_source_info', models.TextField(default='')),
                ('var_timespan', models.TextField(default='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.Harmonisation_Variables')),
            ],
        ),
    ]
