# Generated by Django 2.2.5 on 2020-10-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0035_auto_20201014_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harmdata',
            name='model',
        ),
        migrations.RemoveField(
            model_name='harmdata',
            name='variable',
        ),
        migrations.DeleteModel(
            name='DatasetVariableHarmonisation',
        ),
        migrations.DeleteModel(
            name='HarmData',
        ),
    ]
