# Generated by Django 3.0.7 on 2020-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0036_auto_20201014_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmdatanew',
            name='var_source_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionsres',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='regionsres',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scenariosres',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scenariosres',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unitsres',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='unitsres',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variablesres',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='variablesres',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
