# Generated by Django 3.0.7 on 2020-10-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0037_auto_20201020_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscomp',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels'),
        ),
    ]
