# Generated by Django 3.0.7 on 2020-10-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0039_auto_20201020_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariosres',
            name='scenario',
        ),
    ]
