# Generated by Django 3.0.5 on 2020-10-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0040_remove_scenariosres_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harmdatanew',
            name='var_source_info',
        ),
        migrations.RemoveField(
            model_name='harmdatanew',
            name='var_source_url',
        ),
        migrations.CreateModel(
            name='HarmDataSourcesLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_source_url', models.TextField(default='')),
                ('var_source_info', models.TextField(default='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.Harmonisation_Variables')),
            ],
        ),
    ]
