# Generated by Django 3.0.5 on 2020-10-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0041_auto_20201022_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultscomp',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='resultscomp',
            old_name='scenario_id',
            new_name='scenario',
        ),
        migrations.RenameField(
            model_name='resultscomp',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='resultscomp',
            old_name='variable_id',
            new_name='variable',
        ),
        migrations.RemoveField(
            model_name='resultscomp',
            name='model_id',
        ),
        migrations.AddField(
            model_name='resultscomp',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels'),
        ),
    ]
