# Generated by Django 3.0.5 on 2020-12-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0042_auto_20201030_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmDataSourcesTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='harmdatasourceslinks',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.HarmDataSourcesTitles'),
            preserve_default=False,
        ),
    ]
