# Generated by Django 3.0.5 on 2020-12-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0043_auto_20201202_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.RegionsRes')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ScenariosRes')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.VariablesRes')),
            ],
        ),
    ]
