# Generated by Django 3.0.7 on 2021-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0044_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRWMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=50)),
                ('model_title', models.CharField(default='', max_length=50)),
                ('scenario_name', models.CharField(default='', max_length=50)),
                ('scenario_title', models.CharField(default='', max_length=50)),
                ('region_name', models.CharField(default='', max_length=50)),
                ('region_title', models.CharField(default='', max_length=50)),
                ('variable_name', models.CharField(default='', max_length=50)),
                ('variable_title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MetaData',
        ),
    ]
