# Generated by Django 3.0.7 on 2021-02-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0045_auto_20210201_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prwmetadata',
            name='model_title',
        ),
        migrations.RemoveField(
            model_name='prwmetadata',
            name='region_title',
        ),
        migrations.RemoveField(
            model_name='prwmetadata',
            name='scenario_title',
        ),
        migrations.RemoveField(
            model_name='prwmetadata',
            name='variable_title',
        ),
    ]
