# Generated by Django 3.0.7 on 2021-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0046_auto_20210201_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesres',
            name='agg_func',
            field=models.CharField(default='', max_length=20),
        ),
    ]
