# Generated by Django 3.0.7 on 2021-03-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0048_regionsres_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesres',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VaraiblesSdgsRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.SdgsCat')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.VariablesRes')),
            ],
        ),
    ]
