# Generated by Django 3.0.7 on 2021-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0049_auto_20210316_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablesres',
            name='important',
        ),
        migrations.AddField(
            model_name='variablesres',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
