# Generated by Django 2.2.5 on 2021-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0050_auto_20210316_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='RrfPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.TextField(default='')),
                ('axis', models.TextField(default='')),
                ('rff_type', models.CharField(default='', max_length=50)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('budget', models.FloatField()),
                ('total_ratio', models.FloatField()),
                ('country', models.CharField(default='', max_length=50)),
                ('first_classification', models.CharField(default='', max_length=50)),
                ('second_classification', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
