# Generated by Django 2.2.5 on 2021-09-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0052_auto_20210713_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=50)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ModelsInfo')),
            ],
        ),
    ]
