# Generated by Django 2.2.5 on 2021-09-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0053_projectmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodels',
            old_name='model_id',
            new_name='model',
        ),
    ]
