# Generated by Django 2.2.5 on 2021-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0054_auto_20210924_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRWEUMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=50)),
                ('scenario_name', models.CharField(default='', max_length=50)),
                ('region_name', models.CharField(default='', max_length=50)),
                ('variable_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
