# Generated by Django 2.2.5 on 2021-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0056_auto_20211004_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodelgeoguides',
            name='workspace',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datasetmodeltimestepguides',
            name='workspace',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datasetmodeltypeguides',
            name='workspace',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datasetvariableharmonisationguides',
            name='workspace',
            field=models.CharField(default='', max_length=50),
        ),
    ]
