# Generated by Django 2.2.5 on 2022-11-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0062_feasibilitymetadata_feasibilityresultscomp'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDAResultsComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.DataVariablesModels')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.RegionsRes')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.ScenariosRes')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.UnitsRes')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2amparis_main.VariablesRes')),
            ],
        ),
    ]
