# Generated by Django 2.2.5 on 2023-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0064_ndcametadata_ndcaresultscomp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NDCAMetaData',
        ),
    ]
