# Generated by Django 2.2.5 on 2023-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0065_delete_ndcametadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDCAMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=100)),
                ('scenario_name', models.CharField(default='', max_length=100)),
                ('region_name', models.CharField(default='', max_length=100)),
                ('variable_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
