# Generated by Django 2.2.5 on 2020-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(default='', max_length=50)),
                ('parameters', models.TextField(default='{}', max_length=1000, null=True)),
            ],
        ),
    ]
