# Generated by Django 2.2.5 on 2022-10-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_query_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='dataset',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
